name: Build

on:
  push:
    branches: [ "armbuild" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  wxBUILD_SHARED: OFF
  wxBUILD_USE_STATIC_RUNTIME: ON 

jobs:
  build-win32-msvc2019:
    
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
  
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "Visual Studio 16 2019" -A Win32 -T v141_xp -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxBUILD_SHARED=${{env.wxBUILD_SHARED}} -DwxBUILD_USE_STATIC_RUNTIME=${{env.wxBUILD_USE_STATIC_RUNTIME}} 

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2
      
    - uses: actions/upload-artifact@v3
      with:
        name: windows_bin_x86
        path: ${{github.workspace}}/build/app/Release/DeltaPatcher.exe
      
  build-linux:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Pull dependencies
      run: sudo apt install -y build-essential cmake git libgtk-3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxBUILD_SHARED=${{env.wxBUILD_SHARED}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2
      
#    - name: Package AppImage
#      run: ${{github.workspace}}/utils/make-appimage.sh ${{github.workspace}}/build ${{github.workspace}} DeltaPatcher
      
    - uses: actions/upload-artifact@v3
      with:
        name: linux_bin_gtk3_x86_64
        path: ${{github.workspace}}/build/app/DeltaPatcher

  build-macos1015:
    
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxBUILD_SHARED=${{env.wxBUILD_SHARED}} -DwxBUILD_USE_STATIC_RUNTIME=${{env.wxBUILD_USE_STATIC_RUNTIME}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2
        cd ${{github.workspace}}/build/app
        zip -r macos10.15_bin_x86_64.zip DeltaPatcher.app/
      
      
    - uses: actions/upload-artifact@v3
      with:
        name: macos10.15_bin_x86_64
        path: ${{github.workspace}}/build/app/macos10.15_bin_x86_64.zip
  
  build-macos11-universal:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxBUILD_SHARED=${{env.wxBUILD_SHARED}} -DwxBUILD_USE_STATIC_RUNTIME=${{env.wxBUILD_USE_STATIC_RUNTIME}}

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 2
        cd ${{github.workspace}}/build/app
        zip -r macos11_bin_universal.zip DeltaPatcher.app/
      
      
    - uses: actions/upload-artifact@v3
      with:
        name: macos11_bin_universal
        path: ${{github.workspace}}/build/app/macos11_bin_universal.zip
